components/AboutCairoVMBanner.tsx, components/ChainSelector.tsx, components/Editor/ExecutionStatus.tsx, components/Editor/Header.tsx, components/Editor/Instructions.tsx, components/Editor/index.tsx, components/Editor/types.ts, components/Reference/DocRow.tsx, components/Reference/DynamicFee.tsx, components/Reference/index.tsx, components/ThemeSelector.tsx, components/ToggleFullScreen.tsx, components/Tracer/ExecutionStatus.tsx, components/Tracer/index.tsx, components/layouts/Home.tsx, components/layouts/Nav.tsx, components/ui/Container.tsx, components/ui/Input.tsx, components/ui/Message.tsx, context/ethereumContext.tsx, lib/useActions.tsx, package.json, pages/_app.tsx, pages/about.tsx, pages/index.tsx, util/constants.ts
Related to https://github.com/walnuthq/cairovm.codes/issues/12
To ease this process, I've added a new npm script `lint:fix` which calls the linter with the `--fix` option (using `npm run lint --fix` does not work because the `--fix` option must be before the path `.`).
I also removed unused code in comments as these portions of code were direclty linked to the linter warnings (useless imports, useless variables and so on).
The dynamic fee documentation part in the `DocRow` component was not used but as it was quite big, I removed it in a dedicated commit. If it has to be kept for a future implementation, I can comment all of this to avoid having linter errors/warnings on it.
=> [chore] fix linter errors and warnings

components/Editor/EditorControls.tsx, components/Editor/index.tsx, components/ui/Input.tsx, context/cairoVMApiContext.tsx, util/compiler.ts, util/constants.ts
related to https://github.com/walnuthq/cairovm.codes/issues/17
A new input field accepts program arguments separated by a whitespace. Each parameter could be a single value (i.e a `felt252`) or an array of values (i.e array of `felt252`).
I used the whitespace instead of the coma as separator because, on the back-end side, the argument parsing was already implemented in the `process_args` function. Of course, it can be adapted if needed !
That means:
* every parameters are separated by a space
* a parameter could be a single felt252 or an array of felt252
* every items in an array are separated by a space.
For example `1 [3 4 5] 9` contains 3 parameters.
The user input is sanitized (extra whitespaces are removed) and validated (text input in red if not valid and the 'run' button is …
=> feat: add support of program arguments

.github/workflows/ci.yml, .husky/pre-commit, package.json
Related to https://github.com/walnuthq/cairovm.codes/issues/45.
The `--max-warnings=0` option has been added to lint scripts in `package.json` in order to consider a warning as an error when linting the project. Thanks to that, the Github action and the Husky pre-commit hook will fail in case of warnings.
=> chore: add a Github action to typecheck and lint a PR

components/Editor/ArgumentsHelperModal.tsx, components/Editor/EditorControls.tsx, components/Editor/index.tsx, components/ui/Modal.tsx
To fix this overlapping issue I moved the "arguments" modal from the `EditorControls` component to the end of the `Editor` component, as it's always better to extract modals from deep `div` hierarchies.
At the same time, I've created a dedicated component for this modal, to avoid "polluting" the `Editor` component file.
I've also set specific colors for the modal in dark mode.
=> chore: fix trace table ovelapping the arguments modal

components/AboutCairoVMBanner.tsx
The feature to hide the about banner when closed was already implemented but the local storage flag was never set.
This PR sets the flag in the local storage.
=> fix: set banner closed in local storage

components/Editor/Header.tsx, components/ui/Button.tsx
Fix #50 based on this https://github.com/ReactTooltip/react-tooltip/issues/587#issuecomment-619675399
After this error, there was another server-rendering issue with react-select “Warning: Prop `id` did not match” that I fixed with a fixed instanceId. A better fix would be to use the useId() hook but it's only available on React 18.
`import React, { useId } from 'react';`
There is one remaining issue for mac devices only I think `Extra attributes from the server: aria-activedescendant`.
Everything seems linked to the fact that react-select does not render isomorphically.
There is [an attempt to fix it](https://github.com/JedWatson/react-select/issues/5859) specifically here, I'd suggest to wait and see if the PR get merged
=> [fix] fix dangerously error on landing

components/Editor/EditorControls.tsx, components/KBar/Button.tsx, components/KBar/Results.tsx, components/KBar/index.tsx, components/ThemeSelector.tsx, components/ToggleFullScreen.tsx, components/Tracer/ExecutionStatus.tsx, components/layouts/Nav.tsx, lib/useActions.tsx
Fix #53 
Two possibilities:
- display kbar by clicking on the K button in the navbar or pressing Ctrl+K (Cmd+K for mac users), and select one option in the menu
- directly run shortcuts from the homepage
Basically you can just load the page and:
- type "f" to enter/exit full screen mode
- type "r" to compile and run
- type "n" and "b" to step next and back on the execution
- type "c" to continue execution
=> Bring back kbar

.github/workflows/preview.yml
This PR adds a Github action `Vercel / Preview` which build and deploy the cairovm.codes front-end to Vercel for every PR.
A button `View Deployment` is automatically posted on the PR by the Vercel bot.
Note to configure Github and Vercel properly:
* First of all, you need to install the Vercel CLI tool:
* `npm i -g vercel@latest`
* In your local git checkout of `cairovm.codes`, enter `vercel login` to log in to Vercel and then `vercel link` to create the project on Vercel and generate a `.vercel` folder in local (this folder is ignored by git).
* Go in the settings panel of your Vercel account on vercel.com. In Tokens, create a new one dedicated to `cairovm.codes` and don't forget to copy it.
* Go to the settings of the `cairovm.codes` repository on Github. In "Secrets and Variables" > …
=> [chore] add Vercel preview for PRs

.github/workflows/ci.yml, .github/workflows/preview.yml
This PR fixes several issues:
- now, vercel preview uses the correct repo and branch in `actions/checkout@v3` to checkout the code associated to the PR.
- both actions "vercel preview" and "lint" are triggered at PR opening **and** each time the branch associated to the PR is updated (Github event `synchronize`).
To allow anyone accessing the Vercel preview URL, go on vercel.com in the project settings. Go to "Deployment protection" and disable "Vercel Authentication".
=> chore: fix Github actions

components/Editor/index.tsx
closes #96 
- allows for commenting/uncommenting single/multiple lines
- preserves cursor position/selection
=> handle comment/uncomment line via shortcut

components/Tracer/index.tsx, components/ui/Modal.tsx
=> fix: resolve thead overlay issue on scroll - issue #92

components/Editor/ArgumentsHelperModal.tsx, components/ui/Modal.tsx
Fixes #113, I didn't find code blocks in evm.codes so I asked AI for recommandations for a good color palette that fit with native tailwind CSS colors. Result seems good to me, feel free to challenge 
Light
Dark
=> :lipstick: make modal pretty on dark mode

components/Editor/EditorControls.tsx, components/Editor/ExampleSelector.tsx, components/Editor/examples.ts, components/Editor/index.tsx
Resolves #127  
Refactored Example Selector
Utilised `react-select` as we are already using it for a dropdown of CodeType.
=> Refactor: Example Selector

components/Editor/cairoLangConfig.ts, components/Editor/index.tsx
=> chore: editor dark theme in dark mode

components/Editor/examples.ts, components/Tracer/index.tsx
#143
The parameters are now displayed in the callstack table.
=> feat: Display call parameters in the callstack table - Issue #143

components/Editor/EditorControls.tsx, components/Editor/EditorFooter.tsx, components/Editor/index.tsx, components/KBar/Button.tsx, components/ThemeSelector.tsx, components/ToggleFullScreen.tsx, components/ToggleThreeColumnLayout.tsx, components/Tracer/index.tsx, components/layouts/Nav.tsx
=> chore: style and mobile ui improvements

components/Editor/index.tsx, components/Tracer/index.tsx, context/cairoVMApiContext.tsx
Resolves #145 
I had to move up `setLogs(data.logs)` to get the logs.
I dont know if this is a known issue but whenever compilation fails, it throws error in the below code segment because `is_execution_successful` & `tracer_data` in `data` is undefined as not returned by the `run` API and it would jump to catch block thus not updating the logs.
Also added a small style fix because in some screens console log messages were being cutoff like this
=> fix: compile and runtime error messaging

components/Editor/InstructionsTable.tsx
#154
This bug was found not only in sierra Extracolumn, it was also reproduced in the casm table. The problem was the incorrect line break and line width. I have corrected this behavior.
=> Bug: in three column layout when device width is 1028px, the sierra column breaks - Issue #154

components/Tracer/index.tsx
I removed an extra row from the table using the condition: callstackEntry.fn_name || debugMode === ProgramDebugMode.Execution
=> Bug: An empty row in the debug info table in debug sierra mode - Issue #162

components/Editor/Console.tsx, components/Editor/Header.tsx, components/layouts/Nav.tsx
#165 
The task is completed, and additionally I fixed a bug due to which the drop-down menu could overlap the page header.
=> Bug: Automatic scrolling in the console - Issue #165

components/Editor/index.tsx, package-lock.json, package.json
#167 
The problem was solely related to the telegram application on macbooks downloaded from the App store. The decision took a lot more effort than I expected. In the end, I figured out what the problem was, in this case, telegram very selectively allows you to insert links with base64 encoding, so standard methods like btoa() and encodeURIComponent() will not work here. The LZString library came to the rescue with its compressToEncodedURIComponent method, the encoding of which allows you to correctly insert links both in telegram on windows and in telegram on macbooks.
I also added DebugMode to the links, there was no difficulty with that.
=> chore: Improve permalinks - Issue #167

util/browser.ts
Resolves #174 
Also did a lighthouse report and everything seems good to me except a few things firstly something we all forget and care less, which is adding more "Accessibility" obviously and The best practices score is less because it looks like the text area of monaco editor gets flagged as some field which don't allow user to paste anything.
I would also suggest to check Google Search Console, you might find some interesting insights for the website such as indexing of pages and much more and we can add keywords meta tag too.
=> fix: production url

components/Editor/Console.tsx, components/Editor/EditorControls.tsx, components/Editor/EditorFooter.tsx, components/Editor/ExampleSelector.tsx, components/Editor/ExtraColumn.tsx, components/Editor/InstructionsTable.tsx, components/Editor/cairoLangConfig.ts, components/Editor/index.tsx, components/KBar/ResultItem.tsx, components/Tracer/ExecutionStatus.tsx, components/Tracer/index.tsx, components/ui/Button.tsx, components/ui/Input.tsx, pages/_document.tsx, styles/globals.css, tailwind.config.js
The colors for the dark theme were redesigned, the colors of the buttons were changed, and the IBM PLEX SANS font was added. Scrollbars have also been redesigned.
=> Redesign: colors, typography, button backgrounds

components/Editor/EditorFooter.tsx, components/Editor/Header.tsx, components/Editor/index.tsx, context/appUiContext.tsx, pages/cairo-lang/index.tsx
The cairo-lang page has been added, where it is impossible to exit full-screen mode, the k-bar button has been removed and the necessary changes have been made in accordance with Figma
=> Redesign: special handle for cairo-lang - Issue #178

components/Editor/EditorFooter.tsx, components/Editor/Header.tsx
Elements from header were returned to footer
=> Fixed cairo-lang page

components/Tracer/index.tsx, components/ui/MultiButton.tsx, context/cairoVMApiContext.tsx
=> Fix: compile bugs
